### ISSUE TITLE
Remove provider version in autoscale module

### ISSUE THREAD

**Issue by lstadnik** [PaloAltoNetworks/terraform-google-vmseries-modules#115]
## Describe the bug

The version of ```null``` and ```random``` providers are in conflict in different module (bootstrap).

## Expected behavior

The provider version should start from 3.1

## Current behavior

null | ~> 2.1
random | ~> 2.3

## Possible solution

Update the autoscale module.

## Your Environment

[null](https://github.com/PaloAltoNetworks/terraform-google-vmseries-modules/tree/develop/modules/autoscale#requirement_null)	~> 2.1
[random](https://github.com/PaloAltoNetworks/terraform-google-vmseries-modules/tree/develop/modules/autoscale#requirement_random)	~> 2.3

**Comment by migara** [comment]
Resolved in #116
