### ISSUE TITLE
The vmseries module fails with "Cross-project references for this resource are not allowed"

### ISSUE THREAD

**Issue by darrenmillin** [PaloAltoNetworks/terraform-google-vmseries-modules#131]
When deploying the vmseries module through a Jenkins pipeline, the deployment fails with "Cross-project references for this resource are not allowed". This was resolved by adding the project parameter to the following resources in modules/vmseries/main.tf:

data "google_compute_image" "vmseries" on line 11
data "google_compute_subnetwork" "this" on line 18
resource "google_compute_address" "private" on line 24
resource "google_compute_address" "public" on line 30

**Comment by michalbil** [comment]
Hello @darrenmillin!

Thank you for your report. Can you please provide more insight into your use case, including how is the module called and some info about relation to other GCP project(s)?

**Comment by michalbil** [comment]
Hello @darrenmillin!

Thank you for your report. Can you please provide more insight into your use case, including how is the module called and some info about relation to other GCP project(s)?
