### ISSUE TITLE
Bump hashicorp/google provider version to 4.x

### ISSUE THREAD

**Issue by mazwettler** [PaloAltoNetworks/terraform-google-vmseries-modules#147]
Currently all modules have following version constraint defined:
```
terraform {
  required_version = ">= 0.15.3, < 2.0"

  required_providers {
    null   = { version = "~> 3.1" }
    google = { version = "~> 3.30" }
  }
}
```

However the latest version of the 3.x google provider was released over a year ago and version 4.x was released on Nov 2, 2021.

I think it would be time to bump the modules to 4.x provider version to be able to use this module in terraform projects which also deploy new resources added in 4.x.

BR,
Markus

**Comment by migara** [comment]
Let's do this at the same time we work on #144
