### ISSUE TITLE
location of "google_storage_bucket" in module "bootstrap" not set - defaults to "US"

### ISSUE THREAD

**Issue by mazwettler** [PaloAltoNetworks/terraform-google-vmseries-modules#148]
### Is your feature request related to a problem?

Currently all storage buckets created in the module "bootstrap" have the location argument not set, which leads to it defaulting to "US".
https://registry.terraform.io/providers/hashicorp/google/3.90.1/docs/resources/storage_bucket

### Describe the solution you'd like

The bootstrap module should take a GCP location as input and use that to deploy the bootstrap bucket into the specified location.

### Additional context

Many customers have location restrictions defined in their GCP projects which leads to errors like this:
` Error: googleapi: Error 412: 'us' violates constraint 'constraints/gcp.resourceLocations', conditionNotMet`
 
when trying to deploy a VM-Series firewall with the module from this repository.

Also, with the current version of the hashicorp/google provider this argument becomes required - so this would also make it easier to bump the provider version of the module up to 4.x.

**Comment by michalbil** [comment]
Fixed in #150
