### ISSUE TITLE
Changing machine_type doesn't trigger a rebuild of the vm-series

### ISSUE THREAD

**Issue by ntwrkguru** [PaloAltoNetworks/terraform-google-vmseries-modules#152]
## Describe the bug

Changing the `machine_type` variable in the `vmseries_common` object has no effect.

## Expected behavior

Changing the machine_type, should trigger a change to the instance.

## Current behavior

Changing the `machine_type` variable in the `vmseries_common` object has no effect.

## Steps to reproduce

1. Change `machine_type` in `vmseries_common` and execute a terraform plan/apply

## Context

Requires a destroy/apply to update instance type

**Comment by migara** [comment]
@ntwrkguru is this [common_firewall](https://github.com/PaloAltoNetworks/terraform-google-vmseries-modules/tree/main/examples/common_firewall) or [hub_spoke_common](https://github.com/PaloAltoNetworks/terraform-google-vmseries-modules/tree/main/examples/hub_spoke_common)?
