### ISSUE TITLE
Conditional Disk support for Panorama

### ISSUE THREAD

**Issue by seanyoungberg** [PaloAltoNetworks/terraform-google-vmseries-modules#29]
For Panorama VM creation, we need to have the ability to conditionally create n number of 2TB disk attachments.

Some customers may be running in management only and need 0 disks created.

When a customer is doing logging on panorama, they will typically start with a single 2TB disk, but then others can later be added if needed for more logging space. Due to the limitations of Panorama, it only is support to add disks in 2TB

Hopefully this can be done with GCP provider in a way where additional disks can be added to an existing VM without forcing recreation of the VM.

**Comment by migara** [comment]
Fixed in #75
