### ISSUE TITLE
Multiple google_compute_firewall

### ISSUE THREAD

**Issue by jabielecki** [PaloAltoNetworks/terraform-google-vmseries-modules#5]
https://spring.paloaltonetworks.com/jbielecki/tfmono/blob/2d483dc24de7fe3eca054c209b2abaa7945d3a8b/modules/gcp/vpc/main.tf#L15-L26

Perhaps we should enable creation of multiple `google_compute_firewall` resources the same way we have done here 
https://spring.paloaltonetworks.com/mekanayake/terraform-aws-vpc/blob/ac92346ef57de9f9fe0e48eab4d1079ea3081210/main.tf#L115-L153

Originally requested by @migara in https://spring.paloaltonetworks.com/jbielecki/tfmono/issues/26

**Comment by migara** [comment]
This is supported in the new vpc module
