### ISSUE TITLE
Update Terraform versions to latest (12.x -> 1.x)

### ISSUE THREAD

**Issue by devsecfranklin** [PaloAltoNetworks/terraform-google-vmseries-modules#69]
## Describe the bug

We need the Terraform versions updated in the modules. We are expected to deliver customer projects in GCP with these modules.

## Expected behavior

At least Terraform 1.0.8 at the time of this writing.

## Current behavior

We would have to ask our customer to use Terraform 12.x in cloud shells and local env.

**Comment by migara** [comment]
This is resolved now
